// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzBL4BPMNVilyzTJVH4QFc2JahmEI3a6M',
    appId: '1:306945729834:web:267ae9c82572612189aa53',
    messagingSenderId: '306945729834',
    projectId: 'kelompocky',
    authDomain: 'kelompocky.firebaseapp.com',
    storageBucket: 'kelompocky.appspot.com',
    measurementId: 'G-Z37CV68N7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWmzrvxSvWFFvtA_zNQpJYZYR-YSkEYL4',
    appId: '1:306945729834:android:fe27d75494591f2789aa53',
    messagingSenderId: '306945729834',
    projectId: 'kelompocky',
    storageBucket: 'kelompocky.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEYr5kQYNDWso6ujRUYZWYNpf0C22TPes',
    appId: '1:306945729834:ios:a4ef3b3f17fd344d89aa53',
    messagingSenderId: '306945729834',
    projectId: 'kelompocky',
    storageBucket: 'kelompocky.appspot.com',
    androidClientId: '306945729834-f5e16pb9q5s4r6gkk9tne775c3g39rle.apps.googleusercontent.com',
    iosClientId: '306945729834-eqqvkij4sj1f9s56vtqq0opk085eibmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kelompockyTarukkin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEYr5kQYNDWso6ujRUYZWYNpf0C22TPes',
    appId: '1:306945729834:ios:a4ef3b3f17fd344d89aa53',
    messagingSenderId: '306945729834',
    projectId: 'kelompocky',
    storageBucket: 'kelompocky.appspot.com',
    androidClientId: '306945729834-f5e16pb9q5s4r6gkk9tne775c3g39rle.apps.googleusercontent.com',
    iosClientId: '306945729834-eqqvkij4sj1f9s56vtqq0opk085eibmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kelompockyTarukkin',
  );
}
